# github workflow to automate builds

name: Golang

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Windows build

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Sets Go version to use
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Fetch Git tags
        shell: cmd
        run: git fetch --prune --unshallow --tags

      # Runs commands using the runners shell
      - name: Build
        shell: cmd
        run: |
            cd cmd\play
            go build

      # upload to "actions" tab artifacts (can only make a single .zip from a dir's files)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: play
          path: ${{github.workspace}}\cmd\play\play.exe
